package br.com.sysdesc.util.constants;

public class MensagemConstants {

	public static final String MENSAGEM_NENHUM_REGISTRO_ENCONTRADO = "MENSAGEM_NENHUM_REGISTRO_ENCONTRADO";
	public static final String MENSAGEM_INSIRA_DESCRICAO_VALIDA = "MENSAGEM_INSIRA_DESCRICAO_VALIDA";
	public static final String MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_VALIDA = "MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_VALIDA";
	public static final String MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_MAXIMO_TRES = "MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_MAXIMO_TRES";
	public static final String MENSAGEM_SELECIONE_DEPARTAMENTO = "MENSAGEM_SELECIONE_DEPARTAMENTO";
	public static final String MENSAGEM_SELECIONE_CATEGORIA = "MENSAGEM_SELECIONE_CATEGORIA";
	public static final String MENSAGEM_SELECIONE_SUBCATEGORIA = "MENSAGEM_SELECIONE_SUBCATEGORIA";
	public static final String MENSAGEM_SELECIONE_ESTADO = "MENSAGEM_SELECIONE_ESTADO";
	public static final String MENSAGEM_SELECIONE_MARCA = "MENSAGEM_SELECIONE_MARCA";
	public static final String MENSAGEM_SELECIONE_UNIDADE = "MENSAGEM_SELECIONE_UNIDADE";
	public static final String MENSAGEM_VALOR_ESTOQUE_MINIMO_MAIOR_MAXIMO = "MENSAGEM_VALOR_ESTOQUE_MINIMO_MAIOR_MAXIMO";

}
