package br.com.sysdesc.util.constants;

public class MensagemConstants {

	public static final String MENSAGEM_NENHUM_REGISTRO_ENCONTRADO = "MENSAGEM_NENHUM_REGISTRO_ENCONTRADO";
	public static final String MENSAGEM_INSIRA_DESCRICAO_VALIDA = "MENSAGEM_INSIRA_DESCRICAO_VALIDA";
	public static final String MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_VALIDA = "MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_VALIDA";
	public static final String MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_MAXIMO_TRES = "MENSAGEM_INSIRA_DESCRICAO_REDUZIDA_MAXIMO_TRES";
	public static final String MENSAGEM_SELECIONE_DEPARTAMENTO = "MENSAGEM_SELECIONE_DEPARTAMENTO";
	public static final String MENSAGEM_SELECIONE_CATEGORIA = "MENSAGEM_SELECIONE_CATEGORIA";
	public static final String MENSAGEM_SELECIONE_SUBCATEGORIA = "MENSAGEM_SELECIONE_SUBCATEGORIA";
	public static final String MENSAGEM_SELECIONE_ESTADO = "MENSAGEM_SELECIONE_ESTADO";
	public static final String MENSAGEM_SELECIONE_MARCA = "MENSAGEM_SELECIONE_MARCA";
	public static final String MENSAGEM_SELECIONE_UNIDADE = "MENSAGEM_SELECIONE_UNIDADE";
	public static final String MENSAGEM_VALOR_ESTOQUE_MINIMO_MAIOR_MAXIMO = "MENSAGEM_VALOR_ESTOQUE_MINIMO_MAIOR_MAXIMO";
	public static final String MENSAGEM_SELECIONE_PESQUISA = "MENSAGEM_SELECIONE_PESQUISA";
	public static final String MENSAGEM_SELECIONE_UM_REGISTRO = "MENSAGEM_SELECIONE_UM_REGISTRO";
	public static final String MENSAGEM_SELECIONE_APENAS_UM_REGISTRO = "MENSAGEM_SELECIONE_APENAS_UM_REGISTRO";
	public static final String MENSAGEM_TIPO_DADO_INVALIDO = "MENSAGEM_TIPO_DADO_INVALIDO";
	public static final String MENSAGEM_SELECIONE_FIELD = "MENSAGEM_SELECIONE_FIELD";
	public static final String MENSAGEM_SELECIONE_UMA_FORMATACAO = "MENSAGEM_SELECIONE_UMA_FORMATACAO";
	public static final String MENSAGEM_SELECIONE_FORMATACAO = "MENSAGEM_SELECIONE_FORMATACAO";
	public static final String MENSAGEM_INSIRA_TAMANHO_VALIDO = "MENSAGEM_INSIRA_TAMANHO_VALIDO";
	public static final String MENSAGEM_SELECIONE_PERMISSAO_PESQUISA = "MENSAGEM_SELECIONE_PERMISSAO_PESQUISA";
	public static final String MENSAGEM_INSIRA_PAGINACAO_VALIDA = "MENSAGEM_INSIRA_PAGINACAO_VALIDA";
	public static final String MENSAGEM_PEQUISA_VALIDA = "MENSAGEM_PEQUISA_VALIDA";
	public static final String MENSAGEM_SELECIONE_CAMPO_PESQUISA = "MENSAGEM_SELECIONE_CAMPO_PESQUISA";
	public static final String MENSAGEM_PESQUISA_NAO_CONFIGURADA = "MENSAGEM_PESQUISA_NAO_CONFIGURADA";
	public static final String MENSAGEM_SELECIONE_STATUS = "MENSAGEM_SELECIONE_STATUS";
	public static final String MENSAGEM_DRIVER_NAO_ENCONTRADO = "MENSAGEM_DRIVER_NAO_ENCONTRADO";
	public static final String MENSAGEM_CONEXAO_INVALIDA = "MENSAGEM_CONEXAO_INVALIDA";
	public static final String MENSAGEM_THREAD_VERSAO_INTEROMPIDA = "MENSAGEM_THREAD_VERSAO_INTEROMPIDA";
	public static final String MENSAGEM_ATUALIZAR_VERSAO = "MENSAGEM_ATUALIZAR_VERSAO";

}
